export {default as market} from './market.png'
export {default as store} from './store.png'
export {default as food} from './food.png'
export {default as tm} from './tm.png'
export {default as ru} from './ru.png'
export {default as en} from './en.png'
export {default as apple} from './apple.svg'
export {default as google} from './google.svg'